Public Class Form1

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        Dim ntlst As Integer = ListBox1.Items.Count
        Dim opp = ntlst / 5
        mp = CInt(opp)
        'Timer1.Start()==============
        Dim i As Integer, j As Integer
        Dim dstbox As ListBox = Nothing
        Dim srcbox As ListBox = Me.ListBox1
        'loop through listbox
        For i = 2 To 5
            'set destination listbox
            dstbox = DirectCast(Me.Controls(String.Concat("ListBox", i)), ListBox)
            'move items
            For j = 1 To mp
                'copy last item to ListboxN
                dstbox.Items.Add(srcbox.Items(srcbox.Items.Count() - 1))
                'remove last item from listbox1
                srcbox.Items.RemoveAt(srcbox.Items.Count() - 1)
            Next 'j
        Next 'i
    End Sub
    Dim mp As Integer

    Private Sub Timer1_Tick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Timer1.Tick
        Dim i As Integer, j As Integer
        Dim dstbox As ListBox = Nothing
        Dim srcbox As ListBox = Me.ListBox1
        'loop through listbox
        On Error GoTo 344
        For i = 2 To 5
           'set destination listbox
            dstbox = DirectCast(Me.Controls(String.Concat("ListBox", i)), ListBox)
            'move items
            For j = 1 To mp
                'copy last item to ListboxN
                dstbox.Items.Add(srcbox.Items(srcbox.Items.Count() - 1))
                'remove last item from listbox1
                srcbox.Items.RemoveAt(srcbox.Items.Count() - 1)
            Next 'j
        Next 'i
        Timer1.Stop()
344:
        Exit Sub
    End Sub

    Private Sub Form1_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")
        ListBox1.Items.Add("ght" & "psdjvst" & "013kr" & "pand" & "pand")

    End Sub
End Class
